# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.7.0
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: GitHub
dependency_installation_mode: OCA
generate_requirements_txt: true
include_wkhtmltopdf: false
odoo_version: 14.0
org_name: TREVI Software
org_slug: trevi-software
rebel_module_groups: []
repo_description: This repository contains Human Resource addons developed by TREVI
    Software
repo_name: TREVI Human Resource addons for Odoo
repo_slug: trevi-hr
repo_website: https://github.com/trevi-software/trevi-hr
travis_apt_packages: []
travis_apt_sources: []

